version: "3"

services:
  grafana:
    image: grafana/grafana-oss:8.1.3
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ../aqi-server/data:/data
      - ../grafana/dashboard_model.json:/var/lib/grafana/dashboards/city-aqi/dashboard.json
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true

volumes:
  grafana-storage:
  influxdb-storage:
