version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:8.1.3
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ../../streams-insights/aqi-server/data:/data
      - ../grafana/city-aqi-dashboard.json:/var/lib/grafana/dashboards/city-aqi-dashboard.json
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
    networks:
      - streams_nw

  aqi-server:
    image: rbojan2000/aqi-server:0.1.0
    container_name: aqi-server
    volumes:
      - ../../streams-insights/aqi-server/data:/opt/aqi-server/data
    networks:
      - streams_nw

volumes:
  grafana-storage:


networks:
  streams_nw:
    driver: bridge
    name: streams_nw
    external: true
