version: "3"

services:
  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ../aqi-server/data:/data
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true

volumes:
  grafana-storage:
  influxdb-storage:
