version: "3.3"
services:
  spark-master:
    image: rbojan2000/apache-spark:3.5.0
    ports:
      - "9090:8080"
      - "7077:7077"
      - "22:22"
    volumes:
       - ../transformation:/opt/app/transformation
       - ../load:/opt/app/load
       - ../../data:/opt/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - infrastructure_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

  spark-worker-a:
    image: rbojan2000/apache-spark:3.5.0
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ../transformation:/opt/spark-apps
       - ../load:/opt/app/load
       - ../data:/opt/spark-data

    networks:
      - infrastructure_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

  spark-worker-b:
    image: rbojan2000/apache-spark:3.5.0
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
       - ../transformation:/opt/spark-apps
       - ../load:/opt/app/load
       - ../data:/opt/spark-data
    networks:
      - infrastructure_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

networks:
  infrastructure_nw:
    driver: bridge
    name: infrastructure_nw
    external: true