[METEO]
START_DATE = "2017-01-01"
END_DATE = "2023-12-09"
API = "https://archive-api.open-meteo.com/v1/archive"
DAILY_PARAMS = [
        "weather_code",
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "apparent_temperature_max",
        "apparent_temperature_min",
        "apparent_temperature_mean",
        "sunrise",
        "sunset",
        "daylight_duration",
        "sunshine_duration",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "precipitation_hours",
        "wind_speed_10m_max",
        "wind_gusts_10m_max",
        "wind_direction_10m_dominant",
        "shortwave_radiation_sum",
        "et0_fao_evapotranspiration"
        ]

[AIR]
START_DATE = "2022-07-29"
END_DATE = "2023-12-09"
API = "https://air-quality-api.open-meteo.com/v1/air-quality"
HOURLY_PARAMS = [
        "pm10",
        "pm2_5",
        "carbon_monoxide",
        "nitrogen_dioxide",
        "sulphur_dioxide",
        "ozone",
        "aerosol_optical_depth",
        "dust",
        "uv_index",
        "uv_index_clear_sky",
        "ammonia",
        "alder_pollen",
        "birch_pollen",
        "grass_pollen",
        "mugwort_pollen",
        "olive_pollen",
        "ragweed_pollen"
        ]

[DEFAULT]
TIMEZONE="auto"
SLEEP_TIME=60
