[KAFKA]
TOPICS=["aqicn.city.air.pollutant"]
BOOTSTRAP_SERVERS=["broker:29092"]
SCHEMA_REGISTRY_URL="http://schema-registry:8081"
GROUP_ID="aqi-server"
AUTO_OFFSET_RESET="earliest"
ENABLE_AUTO_COMMIT=false
MAX_POLL_RECORDS=20
BATCH_SIZE=1000
