name: Streams Insights CI

on: [push]

jobs:
  build:
    name: SBT Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    
    - name: Run tests
      run: |
        cd streams-insights/air-quality-analyzer
        sbt test
